apiVersion: v1
kind: ConfigMap
metadata:
  name: s2searchui-env
data:
  NEXT_PUBLIC_DEFAULT_PAGE_NUMBER: "0"
  NEXT_PUBLIC_DEFAULT_PAGE_SIZE: "24"
  NEXT_PUBLIC_DEFAULT_LOAD_SPEED: "0"
  NEXT_PUBLIC_MOBILE_MAX_WIDTH: "458"
  NEXT_PUBLIC_API_URL: "http://s2search-api-service"
  NEXT_PUBLIC_SEARCH_API_ENDPOINT: "/v1/search"
  NEXT_PUBLIC_AUTO_COMPLETE_URL: "/v1/search/AutoSuggest"
  NEXT_PUBLIC_DOCUMENTS_COUNT_URL: "/v1/search/TotalDocumentCount"
  NEXT_PUBLIC_FACET_API_ENDPOINT: "/v1/facet"
  NEXT_PUBLIC_THEME_URL: "/v1/theme/GetThemes"
  NEXT_PUBLIC_THEME_PRIMARY_COLOUR: "#616161"
  NEXT_PUBLIC_THEME_SECONDARY_COLOUR: "#303f9f"
  NEXT_PUBLIC_THEME_NAVBAR_COLOUR: "#64b5f6"
  NEXT_PUBLIC_THEME_LOGO_URL: "https://{{ .Values.Storage.accountName }}.blob.core.windows.net/assets/logos/Square2Digital-Logo-2024.svg"
  NEXT_PUBLIC_THEME_MISSING_IMAGE_URL: "https://{{ .Values.Storage.accountName }}.blob.core.windows.net/temp/assets/image-coming-soon.jpg"
  NEXT_PUBLIC_PLACEHOLDER_TEXT_1: "Lexus blue 2012..."
  NEXT_PUBLIC_PLACEHOLDER_TEXT_2: "White hatchback..."
  NEXT_PUBLIC_PLACEHOLDER_TEXT_3: "Silver Convertible..."
  NEXT_PUBLIC_PLACEHOLDER_TEXT_4: "Nissan grey..."
  NEXT_PUBLIC_PLACEHOLDER_TEXT_5: "Ferrari 599..."
  NEXT_PUBLIC_OCP_APIM_SUBSCRIPTION_KEY: "REDUNDANT"
  NEXT_PUBLIC_ENABLE_CANCELATION_TOKEN: "REDUNDANT"
  NEXT_PUBLIC_DEV_CUSTOMER_ENDPOINT: "REDUNDANT"
  NEXT_PUBLIC_S2SEARCH_API_KEY: "REDUNDANT"
