name: Build Function FeedServices

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: s2search-functions-feedservices
      DOCKERFILE_PATH: ./AzureFunctions/S2Search.Function.FeedServices/Dockerfile

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        # Context is set to the repository root (`.`) so that the Dockerfile can access
        # the entire solution structure (Domain, Services, APIs).
        run: |
          docker build \
            -t ${{ env.IMAGE_NAME }}:latest \
            -f ${{ env.DOCKERFILE_PATH }} \
            . # Set build context to the repository root

      - name: Set image tag from commit SHA
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry with PAT
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Tag Docker image for GHCR
        run: |
          docker tag ${{ env.IMAGE_NAME }}:latest ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
          docker tag ${{ env.IMAGE_NAME }}:latest ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
          docker push ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

  cleanup-ghcr:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      packages: write

    env:
      IMAGE_NAME: s2search-functions-feedservices

    steps:
      - name: Clean up old ${{ env.IMAGE_NAME }} GHCR images
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ env.IMAGE_NAME }}
          package-type: container
          token: ${{ secrets.GHCR_PAT }}
          min-versions-to-keep: 10
          delete-only-untagged-versions: false
